apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: deploy-minikube
  namespace: cicd

spec:

  params:

    - name: BACKEND_IMAGE
      type: string
      description: Docker Hub backend image

    - name: FRONTEND_IMAGE
      type: string
      description: Docker Hub frontend image

    - name: TAG
      type: string
      description: Docker image tag

  workspaces:

    - name: source

  steps:

    - name: deploy

      image: bitnami/kubectl:latest

      workingDir: $(workspaces.source.path)

      script: |
        #!/bin/sh

        set -e

        echo "===================================="
        echo "DEPLOY TO MINIKUBE"
        echo "===================================="

        echo ""
        echo "WORKSPACE:"
        pwd

        echo ""
        echo "FILES:"
        find . -maxdepth 3 -type f | sort

        echo ""
        echo "===================================="
        echo "CHECK KUBERNETES MANIFEST"
        echo "===================================="

        ls -la k8s/

        echo ""
        echo "Backend Image:"
        echo "$(params.BACKEND_IMAGE):$(params.TAG)"

        echo ""
        echo "Frontend Image:"
        echo "$(params.FRONTEND_IMAGE):$(params.TAG)"

        echo ""
        echo "===================================="
        echo "DEPLOY BACKEND"
        echo "===================================="

        kubectl apply \
          -f k8s/backend_deployment.yml \
          -n cicd

        kubectl apply \
          -f k8s/backend-service.yaml \
          -n cicd

        kubectl apply \
          -f k8s/backend-hpa.yaml \
          -n cicd

        echo ""
        echo "===================================="
        echo "DEPLOY FRONTEND"
        echo "===================================="

        kubectl apply \
          -f k8s/frontend_deployment.yml \
          -n cicd

        kubectl apply \
          -f k8s/frontend-service.yaml \
          -n cicd

        echo ""
        echo "===================================="
        echo "UPDATE BACKEND IMAGE"
        echo "===================================="

        kubectl set image \
          deployment/employee-backend \
          backend=$(params.BACKEND_IMAGE):$(params.TAG) \
          -n cicd

        echo ""
        echo "===================================="
        echo "UPDATE FRONTEND IMAGE"
        echo "===================================="

        kubectl set image \
          deployment/employee-frontend \
          frontend=$(params.FRONTEND_IMAGE):$(params.TAG) \
          -n cicd

        echo ""
        echo "===================================="
        echo "WAITING BACKEND ROLLOUT"
        echo "===================================="

        kubectl rollout status \
          deployment/employee-backend \
          -n cicd \
          --timeout=300s

        echo ""
        echo "===================================="
        echo "WAITING FRONTEND ROLLOUT"
        echo "===================================="

        kubectl rollout status \
          deployment/employee-frontend \
          -n cicd \
          --timeout=300s

        echo ""
        echo "===================================="
        echo "DEPLOYMENT SUCCESS"
        echo "===================================="

        echo ""
        echo "PODS:"
        kubectl get pods -n cicd

        echo ""
        echo "SERVICES:"
        kubectl get svc -n cicd

        echo ""
        echo "HPA:"
        kubectl get hpa -n cicd