apiVersion: tekton.dev/v1
kind: Task

metadata:
  name: frontend-build-push
  namespace: cicd

spec:

  params:

    - name: IMAGE
      type: string

    - name: TAG
      type: string

  workspaces:

    - name: source

  steps:

    - name: build-push

      image: gcr.io/kaniko-project/executor:v1.23.2

      args:

        - --dockerfile=$(workspaces.source.path)/ui/Dockerfile-vue

        - --context=$(workspaces.source.path)/ui

        - --destination=docker.io/$(params.IMAGE):$(params.TAG)

        - --destination=docker.io/$(params.IMAGE):latest

        - --cache=true

        - --cache-ttl=24h

        - --verbosity=info

      volumeMounts:

        - name: docker-config
          mountPath: /kaniko/.docker

  volumes:

    - name: docker-config

      secret:

        secretName: dockerhub-secret

        items:

          - key: .dockerconfigjson
            path: config.json
