apiVersion: v1
kind: Service

metadata:
  name: employee-backend
  namespace: dev

spec:
  type: ClusterIP

  selector:
    app: employee-backend

  ports:
    - name: http
      port: 8888
      targetPort: http
